services:
  - type: web
    name: Portfolio-Backend
    runtime: java
    repo: https://github.com/FasilathulFazila/Portfolio-Backend
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_MAIL_USERNAME
        value: fazi82115@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: odkdiihjskfriwfw
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SERVER_PORT
        value: "8080"